using UnityEngine;

public class EnemyScript : MonoBehaviour
{
    Transform player;
    [SerializeField] float moveSpeed = 3f;
    Rigidbody2D rb;
    float bigEnemyHealth = 3f;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        player = GameObject.FindWithTag("Player").transform;
    }

    // Update is called once per frame
    void Update()
    {
        if (player != null)
        {
            Vector2 direction = (player.position - transform.position).normalized;
            rb.MovePosition(rb.position + direction * moveSpeed * Time.fixedDeltaTime);
        }
    }
}
